# Generated by Django 4.0.4 on 2022-08-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Name')),
                ('Date_of_birth', models.DateField(verbose_name='date_of_birth')),
                ('gender', models.CharField(max_length=5, verbose_name='gender')),
                ('phone_number', models.IntegerField(verbose_name='phone_number')),
                ('address', models.TextField(verbose_name='address')),
            ],
        ),
    ]
